alter table public.organizations
  add column if not exists public_widget_key uuid not null default gen_random_uuid(),
  add column if not exists widget_enabled boolean not null default true;

create unique index if not exists organizations_public_widget_key_idx
  on public.organizations(public_widget_key);

create index if not exists contacts_org_external_idx
  on public.contacts(organization_id, external_id);

create table if not exists public.customer_satisfaction (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  score integer not null check (score between 1 and 5),
  comment text,
  created_at timestamptz not null default now(),
  unique (conversation_id)
);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  actor_type text not null default 'user' check (actor_type in ('user','contact','ai','system')),
  action text not null,
  entity_type text not null,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_events_org_time_idx
  on public.audit_events(organization_id, created_at desc);

create table if not exists public.invitations (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  email text not null,
  role text not null default 'agent' check (role in ('admin','agent','viewer')),
  token uuid not null default gen_random_uuid(),
  expires_at timestamptz not null default (now() + interval '7 days'),
  accepted_at timestamptz,
  invited_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (organization_id, email)
);

do $$
declare table_name text;
begin
  foreach table_name in array array['customer_satisfaction','audit_events','invitations']
  loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('drop policy if exists "tenant_select" on public.%I', table_name);
    execute format('create policy "tenant_select" on public.%I for select using (organization_id in (select public.user_organization_ids()))', table_name);
    execute format('drop policy if exists "tenant_insert" on public.%I', table_name);
    execute format('create policy "tenant_insert" on public.%I for insert with check (organization_id in (select public.user_organization_ids()))', table_name);
    execute format('drop policy if exists "tenant_update" on public.%I', table_name);
    execute format('create policy "tenant_update" on public.%I for update using (organization_id in (select public.user_organization_ids()))', table_name);
    execute format('drop policy if exists "tenant_delete" on public.%I', table_name);
    execute format('create policy "tenant_delete" on public.%I for delete using (organization_id in (select public.user_organization_ids()))', table_name);
  end loop;
end $$;
